[project]
name = "consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.40",
    "fastapi[standard]>=0.115.13",
    "gunicorn>=23.0.0",
    "psutil>=7.0.0",
]
