services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
        DEVELOPMENT: 1
    environment:
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - '8000:8000'
    tty: true

  redis:
    image: redis:8.0.2
    ports:
      - "6379:6379"
