[project]
name = "poller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.41",
    "boto3-stubs[sqs]>=1.38.41",
    "requests>=2.32.4",
]
