name: ecr push image

on:
  push:
    branches:
      - main
    paths:
      - src/lambda/**

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_WMS_REFRESH_TOKEN: wms-refresh-token-viz-butterthon-dev
  LAMBDA_WMS_REFRESH_TOKEN: "viz-butterthon-dev-func-func-hello-world-from-image"

jobs:
  push:
    runs-on: ubuntu-latest
    # permissionsがないとOIDCが使えない
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # AWS認証
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}

      # ECR認証
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # src/lambda/wms_refresh_tokenに変更があったかどうかの差分チェック
      - id: check-diff-wms_refresh_token
        name: Check changes in wms_refresh_token
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/lambda/wms_refresh_token/' || true)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      # wms_refresh_tokenのDockerイメージをbuild&push
      - name: build and push docker image to ecr
        if: steps.check-diff-wms_refresh_token.outputs.changed != ''
        working-directory: src/lambda/wms_refresh_token
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_WMS_REFRESH_TOKEN }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          aws lambda update-function-code --function-name ${{ env.LAMBDA_WMS_REFRESH_TOKEN }} --image-uri ${{ env.ECR_REGISTRY }}/${{ env.ECR_WMS_REFRESH_TOKEN }}:$IMAGE_TAG
