name: dev Deploy to Lambda Function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/lambda/**

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  REPOSITORY_PREFIX: viz-butterthon-dev-ecr-
  LAMBDA_PREFIX: viz-butterthon-dev-func-

jobs:
  push:
    runs-on: ubuntu-latest
    # permissionsがないとOIDCが使えない
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # AWS認証
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}

      # ECR認証
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # src/lambda/wms_refresh_tokenに変更があったかどうかの差分チェック
      - id: check-diff-wms_refresh_token
        name: Check changes in wms_refresh_token
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^src/lambda/wms_refresh_token/' || true)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT
        # run: |
        #   CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/lambda/wms_refresh_token/' || true)
        #   echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      # wms_refresh_tokenのDockerイメージをbuild&push
      - name: build and push docker image to ecr
        if: steps.check-diff-wms_refresh_token.outputs.changed != ''
        working-directory: src/lambda/wms_refresh_token
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPOSITORY_PREFIX }}wms_refresh_token
          IMAGE_TAG: ${{ github.sha }}
          LAMBDA_NAME: ${{ env.LAMBDA_PREFIX }}wms_refresh_token
        run: |
          docker build . --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          aws lambda update-function-code --function-name $LAMBDA_NAME --image-uri $REGISTRY/$REPOSITORY:$IMAGE_TAG
