name: github secret example

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - id: show-environment-secrets
        name: Show environment secrets
        env:
          SECRET_EXAMPLE: ${{ secrets.SECRET_EXAMPLE }}
        run: |
          echo "$SECRET_EXAMPLE"
